# Generated by Django 4.1.6 on 2023-03-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_alter_topic_options_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(help_text='笔记内容'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default=4, help_text='笔记主题', on_delete=django.db.models.deletion.SET_DEFAULT, to='learning_logs.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(help_text='主题内容', max_length=200),
        ),
    ]
